
name: 'Terraform Infra Apply'

on:
  pull_request:
    branches: [ "main" ]
    paths: ["infratfcode/**"]

permissions:
  contents: read

jobs:    
 deploy:
    name: Terraform Deploy
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-20.04
    environment: production

    defaults:
      run:
        working-directory: ./app
        shell: bash
        
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Terraform Init
        run: |
            cd terraform
            cd qa
            terraform fmt
            terraform init
      - name: Terraform Plan 
        run: terraform plan -input=false   
      - name: Initialise project and deploy terraform
      #  needs: Terraform Plan
        run: terraform apply --auto-approve=true
